version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: laravel-task-management-api
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
  nginx:
    image: nginx
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: react-task-management-client
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_task_management_apis
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
  node_modules: